<?php
session_start();require_once __DIR__.'/../includes.php';need_login();$msg='';$err='';
if(isset($_GET['logout'])){session_destroy();header('Location:login.php');exit;}
if(isset($_GET['delete'])){$id=$_GET['delete'];$a=get_songs();foreach($a as $k=>$s){if(($s['id']??'')===$id){if(!empty($s['file']))@unlink(__DIR__.'/../'.$s['file']);if(!empty($s['cover']))@unlink(__DIR__.'/../'.$s['cover']);unset($a[$k]);}}save_songs($a);header('Location:index.php');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
$title=trim($_POST['title']??'');$dj=trim($_POST['dj']??'DJSTMusic');$cat=trim($_POST['category']??'DJ Remix');
if($title===''||empty($_FILES['song']['name']))$err='Song title aur MP3 file required hai.';
else{$ext=strtolower(pathinfo($_FILES['song']['name'],PATHINFO_EXTENSION));if(!in_array($ext,['mp3','wav','ogg'],true))$err='MP3/WAV/OGG only.';
elseif($_FILES['song']['error']!==UPLOAD_ERR_OK)$err='Upload failed.';
else{$base=preg_replace('/[^a-zA-Z0-9_-]+/','-',pathinfo($_FILES['song']['name'],PATHINFO_FILENAME));$file='uploads/'.date('YmdHis').'-'.$base.'.'.$ext;
if(move_uploaded_file($_FILES['song']['tmp_name'],__DIR__.'/../'.$file)){$cover='';if(!empty($_FILES['cover']['name'])&&$_FILES['cover']['error']===UPLOAD_ERR_OK){$ce=strtolower(pathinfo($_FILES['cover']['name'],PATHINFO_EXTENSION));if(in_array($ce,['jpg','jpeg','png','webp'],true)){$cover='uploads/'.date('YmdHis').'-cover-'.bin2hex(random_bytes(3)).'.'.$ce;move_uploaded_file($_FILES['cover']['tmp_name'],__DIR__.'/../'.$cover);}}$a=get_songs();array_unshift($a,['id'=>bin2hex(random_bytes(6)),'title'=>$title,'dj'=>$dj,'category'=>$cat,'file'=>$file,'cover'=>$cover]);save_songs($a);$msg='Song successfully uploaded!';}else$err='uploads folder writable hona chahiye.';}}
}
$a=get_songs();?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DJSTMusic Admin</title><link rel="stylesheet" href="../assets/style.css"></head><body><main class="wrap"><div style="display:flex;justify-content:space-between;align-items:center"><h1>🎛 DJSTMusic Admin</h1><a href="?logout=1" class="top a">Logout</a></div>
<?php if($msg):?><div class="about"><?=h($msg)?></div><?php endif;?><?php if($err):?><div class="about" style="border-color:red;color:#f33"><?=h($err)?></div><?php endif;?>
<div class="about"><h2>➕ Upload New Song</h2><form method="post" enctype="multipart/form-data"><input name="title" required placeholder="Song title" style="width:100%;padding:13px;margin:7px 0;background:#080808;color:#fff;border:1px solid #400;border-radius:9px"><input name="dj" value="DJSTMusic" placeholder="DJ Name" style="width:100%;padding:13px;margin:7px 0;background:#080808;color:#fff;border:1px solid #400;border-radius:9px"><input name="category" value="DJ Remix" placeholder="Category" style="width:100%;padding:13px;margin:7px 0;background:#080808;color:#fff;border:1px solid #400;border-radius:9px"><p>MP3/WAV/OGG: <input type="file" name="song" accept=".mp3,.wav,.ogg" required></p><p>Cover: <input type="file" name="cover" accept=".jpg,.jpeg,.png,.webp"></p><button style="padding:13px 20px;background:#e00;color:#fff;border:0;border-radius:10px;font-weight:bold">⬆ Upload</button></form></div>
<h2>Uploaded Songs (<?=count($a)?>)</h2><?php foreach($a as $s):?><div class="about" style="padding:15px"><b><?=h($s['title'])?></b><br><small><?=h($s['dj'])?> • <?=h($s['category'])?></small><br><a href="?delete=<?=h($s['id'])?>" onclick="return confirm('Delete this song?')" style="color:#f33">🗑 Delete</a></div><?php endforeach;?><p><a href="../index.php" style="color:#f33">← Website</a></p></main></body></html>